_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: localhost
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: sourojeet.paul@innoraft.com
smtp_password: ''
smtp_from: sourojeet.paul@innoraft.com
smtp_fromname: 'Drupal Training'
smtp_client_hostname: '0.0.0.0:1025'
smtp_client_helo: Hello
smtp_allowhtml: '0'
smtp_test_address: sourojeetpaul2001@gmail.com
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
