<?php

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * @file
 * Primary module hooks for NodeViewCount module.
 */


/**
 * Implements hook_node_view().
 */
function anonymousviewcount_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $news = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => 'news']);
  $uid = \Drupal::currentUser()->id();
  if ($news && $uid == 0) {
    $db = \Drupal::database();
    $count = $db->select('nodeviewcount', 'nvc')
      ->fields('nvc', ['count'])
      ->execute()->fetchCol();
    $updated = ++$count[0];
    $db->upsert('nodeviewcount')
      ->fields(['nid', 'timestamp', 'count'])
      ->values([
        'nid' => $entity->id(),
        'timestamp' => \Drupal::time()->getCurrentTime(),
        'count' => $updated,
      ])
      ->key('nid')->execute();
  }
}
